spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Fetch size 설정 1+N 문제 임시 해결
        default_batch_fetch_size: 1000
        # Entity에 예약어가 있다면 '' 자동 추가
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #        auto_quote_keyword: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_SECRET}
          scope:
            - user:email
            - read:user


  jackson:
    serialization:
      fail-on-empty-beans : false # 디버깅 용이하게 하기 위한 로깅 레벨 수정
logging.level:
  org.hibernate.SQL: debug
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder: trace
    springframework:
      web.servlet: debug

ADMIN_EMAIL: "${ADMIN_EMAIL}"

jwt:
  key: ${JWT_SECRET_KEY}
ACCESS_TOKEN_EXPIRATION_MINUTES: 20
REFRESH_TOKEN_EXPIRATION_MINUTES: 18000

